"""Shared types for the retrieval engine."""

from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

SourceType = Literal[
    "project",
    "task",
    "experiment",
    "weekly_report",
    "equipment",
    "maintenance",
    "booking",
    "member",
    "learning_plan",
]

ALL_SOURCE_TYPES: list[str] = [
    "project",
    "task",
    "experiment",
    "weekly_report",
    "equipment",
    "maintenance",
    "booking",
    "member",
    "learning_plan",
]

Intent = Literal[
    "general",
    "overview",
    "project_progress",
    "member_progress",
    "tasks",
    "overdue_tasks",
    "experiments",
    "weekly_reports",
    "equipment",
    "maintenance",
    "bookings",
    "learning",
]

TimePreset = Literal[
    "today",
    "this_week",
    "last_week",
    "last_7_days",
    "last_30_days",
    "this_month",
    "all",
]

INTENTS: list[str] = [
    "general",
    "overview",
    "project_progress",
    "member_progress",
    "tasks",
    "overdue_tasks",
    "experiments",
    "weekly_reports",
    "equipment",
    "maintenance",
    "bookings",
    "learning",
]

TIME_PRESETS: list[str] = ["today", "this_week", "last_week", "last_7_days", "last_30_days", "this_month", "all"]


@dataclass
class RetrievalHit:
    """A single permission-filtered local search result."""

    source_type: str
    source_id: int
    title: str
    excerpt: str
    score: float
    url: str | None
    project_id: int | None
    occurred_at: datetime | date | None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_type": self.source_type,
            "source_id": self.source_id,
            "title": self.title,
            "excerpt": self.excerpt,
            "score": round(self.score, 2),
            "url": self.url,
            "project_id": self.project_id,
            "occurred_at": (
                self.occurred_at.isoformat()
                if isinstance(self.occurred_at, (datetime, date))
                else None
            ),
            "metadata": self.metadata,
        }


class RetrievalPlan(BaseModel):
    """Whitelist-validated retrieval plan.

    Instances may come from the rule-based parser or from an LLM query
    planner; either way, only these fields exist and all SQL is generated by
    fixed backend code. The model can never express raw filters.
    """

    intent: Literal[
        "general",
        "overview",
        "project_progress",
        "member_progress",
        "tasks",
        "overdue_tasks",
        "experiments",
        "weekly_reports",
        "equipment",
        "maintenance",
        "bookings",
        "learning",
    ] = "general"
    source_types: list[
        Literal[
            "project",
            "task",
            "experiment",
            "weekly_report",
            "equipment",
            "maintenance",
            "booking",
            "member",
            "learning_plan",
        ]
    ] = Field(default_factory=list)
    member_name: str | None = None
    project_name: str | None = None
    equipment_name: str | None = None
    experiment_no: str | None = None
    keywords: list[str] = Field(default_factory=list)
    time_preset: Literal[
        "today",
        "this_week",
        "last_week",
        "last_7_days",
        "last_30_days",
        "this_month",
        "all",
    ] = "all"
    mine_only: bool = False
